### ISSUE TITLE
关于Hypatia的一些问题

### ISSUE THREAD

**Issue by stevebobaaa** [YuzuApchan/MahjonC-Dream-Citizen-mahjong-party-#1]
您好，不好意思打扰您了。看到您之前也跑过那个Hypatia的程序，我这边跑起来一直不成功，不知您是否有空帮我看看呢？十分感谢！

**Comment by YuzuApchan** [comment]
> 

我只是安装了老版本的Hypatia，然后安装降了依赖的版本。现在还有问题吗？不好意思才看到你的issue。

**Comment by YuzuApchan** [comment]
> 您好，不好意思打扰您了。看到您之前也跑过那个Hypatia的程序，我这边跑起来一直不成功，不知您是否有空帮我看看呢？十分感谢！

我只是安装了老版本的Hypatia，然后安装降了版本的依赖。现在还有问题吗？不好意思才看到你的issue。

**Comment by stevebobaaa** [comment]
十分感谢您的回复！现在安装好像是没问题了，运行那个test已经通过了，但是还有一些问题，不知道您是否方便加个微信交流呢，我的邮箱是3220220646@bit.edu.cn

**Comment by YuzuApchan** [comment]
> 十分感谢您的回复！现在安装好像是没问题了，运行那个test已经通过了，但是还有一些问题，不知道您是否方便加个微信交流呢，我的邮箱是[3220220646@bit.edu.cn](mailto:3220220646@bit.edu.cn)
我对Hypatia的理解也只停留在安装，因为现在没在做卫星，可能没有能力提供更多帮助，不好意思。

**Comment by stevebobaaa** [comment]
好的好的，感谢回复！
